#!/usr/bin/env bash
# shellcheck source=/dev/null
# nathanchance's build-clang script wrapper
# Copyright (C) 2018 Albert I (krasCGQ)
# SPDX-License-Identifier: GPL-3.0-or-later

function build-clang {
    local BUILD_FLAGS INSTALL_ROOT

    # Check if we properly init the submodule
    [[ $(find "${SCRIPTDIR}"/nathan | wc -l) -eq 0 ]] && \
        { warn "Submodule required by this function isn't initialized properly!"; return 1; }

    # Default install root for my notebook's environment
    [[ $(hostname) == KudNotebook ]] && \
        INSTALL_ROOT=/opt/kud

    # Parse parameters
    while [[ ${#} -ge 1 ]]; do
        case ${1} in
            -i|--install-root)
                shift && INSTALL_ROOT=${1} ;;
            *)
                warn "Unrecognized parameter specified: \"${1}\"" ;;
        esac
        shift
    done

    # Is install root specified?
    [[ -n ${INSTALL_ROOT} ]] && \
        BUILD_FLAGS=( "-i" "${INSTALL_ROOT}" )

    # Do inside a subshell to avoid messing with the original environment
    (
        # Source Nathan's common environment script
        . "${SCRIPTDIR}"/nathan/common

        # Run build-clang script
        "${SCRIPTDIR}"/nathan/build-clang "${BUILD_FLAGS[@]}"
    ) || { warn "Something went wrong with the subshell!"; return 1; }
}
