#!/usr/bin/sudo /usr/bin/bash
# VPN kill switch enabler/disabler script for UFW
# Copyright (C) 2018 Albert I (krasCGQ)
# SPDX-License-Identifier: GPL-3.0-or-later

# The script is referenced and inspired from:
# https://thetinhat.com/tutorials/misc/linux-vpn-drop-protection-firewall.html
# Modified to be as dead simple and minimal as possible.

function die {
    [[ -n ${1} ]] && \
        echo "! ${1}"

    exit 1
}

# Do nothing on CTRL-C
trap '' INT

trap die ERR

if [[ ${#} -eq 1 ]]; then
    case ${1} in
        # Disable kill switch
        -d|--disable|off)
            CONFIG=( "default allow outgoing"
                     "delete allow out on tun0" ) ;;

        # Enable kill switch
        -e|--enable|on)
            CONFIG=( "default deny outgoing"
                     "allow out on tun0" ) ;;

        # Suicide
        *)
            die "Invalid parameter specified!" ;;
    esac
else
    die "No or more than one option specified!"
fi

for COMMAND in "${CONFIG[@]}"; do
    # Word splitting is required here.
    # shellcheck disable=SC2086
    ufw ${COMMAND}
done
