#!/usr/bin/sudo /usr/bin/sh
# VPN kill switch enabler/disabler script for UFW
# Copyright (C) 2018 Albert I (krasCGQ)
# SPDX-License-Identifier: GPL-3.0-or-later

# The script is referenced and inspired from:
# https://thetinhat.com/tutorials/misc/linux-vpn-drop-protection-firewall.html
# Modified to be as dead simple and minimal as possible.

case ${1} in
    -d|--disable) # Disable VPN kill switch
                  CONFIG=( "default allow outgoing"
                           "delete allow out on tun0" ) ;;
    -e|--enable)  # Enable VPN kill switch
                  CONFIG=( "default deny outgoing"
                           "allow out on tun0 from any to any" ) ;;
    *)            # Suicide
                  echo "! No option specified!"
                  exit 1 ;;
esac

for COMMAND in "${CONFIG[@]}"; do
    # shellcheck disable=SC2086
    ufw ${COMMAND}
done
