#!/usr/bin/env bash
# Copyright (C) 2018 Albert I (krasCGQ)
# SPDX-License-Identifier: GPL-3.0-or-later

# TODO: Proper build script, this is made solely for mido kernel build for now

# Text styles
BLD=$(tput bold)
RST=$(tput sgr0)

# Run this inside kernel source
if [[ ! -f Makefile ]] || [[ ! -d kernel ]]; then
    echo " ${BLD}! Please run this script inside kernel source folder.${RST}"
    exit 1
fi

# Import Telegram bot token & chat ID
SCRIPTDIR=${HOME}/KudProject/scripts
TOKEN=$(cat ${SCRIPTDIR}/tg_token)
CHATID=$(cat ${SCRIPTDIR}/tg_chatid)

# Default message
MSG="KudKernel build:"

# Report progress to a Telegram chat
function tg_sendinfo() {
    curl -s -X POST https://api.telegram.org/bot${TOKEN}/sendMessage \
         -d text="${1}" \
         -d chat_id=${CHATID} >> /dev/null
}

# Whenever build is interrupted by purpose, report it
trap '{
    tg_sendinfo "$(echo -e "${MSG} Interrupted - Signal Interrupt\n@krasCGQ Y u do dis ?? >_<")"
    exit -1
}' INT

# Whenever errors occured, report them
function tg_senderror() {
    tg_sendinfo "$(echo -e "${MSG} Interrupted - Build Error(s)\n@krasCGQ check console desu !! >_<")"
    exit 1
}

trap tg_senderror ERR

# Alert for script startup
tg_sendinfo "${MSG} Started!"

# Begin script
echo " - Setting up environment variables..."
sleep 1

# Unset CROSS_COMPILE and CCOMPILE if they're set
[[ ! -z ${CROSS_COMPILE} ]] && unset CROSS_COMPILE
[[ ! -z ${CCOMPILE} ]] && unset CCOMPILE

# Use ccache when available
if false; then
[[ $(which ccache > /dev/null 2>&1; echo $?) -eq 0 ]] && CCOMPILE+="ccache "
fi

# Whenever you're high enough to run this script
if [[ $(which aarch64-linux-gnu-gcc > /dev/null 2>&1; echo $?) -eq 0 ]]; then
    CCOMPILE+=aarch64-linux-gnu-
else
    tg_senderror
fi

## Always ARM64
ARCH=arm64
## Out directory
OUT=../build/mido
## Always use all threads
THREADS=$(nproc --all)
## Kernel defconfig
#CONFIG="mido_defconfig"
## clang specific values
CTRIPLE=aarch64-linux-gnu-
# FIXME
CC=/opt/kud/flash-clang-7.x/bin/clang
## AnyKernel2
AK2=../../../AnyKernel2
## DTB
DTB=msm8953-qrd-sku3-mido

## Export custom compiler string
export KBUILD_COMPILER_STRING=$(${CC} --version | head -n 1 | perl -pe 's/\(http.*?\)//gs' | sed -e 's/  */ /g' -e 's/[[:space:]]*$//')

echo " - Cleaning build directory..."
sleep 1

# TODO: Completely clean build?
make ARCH=${ARCH} O=${OUT} clean > /dev/null

# Let's build!
echo " - Building kernel..."
make ARCH=${ARCH} O=${OUT} CC="ccache ${CC}" CLANG_TRIPLE=${CTRIPLE} \
     CROSS_COMPILE="${CCOMPILE}" -j${THREADS} > /dev/null

echo " - Cleaning up AnyKernel2 folder..."
rm -rf ${AK2}/{kernel,treble-*}/*

echo " - Copying kernel image and dtbs to AnyKernel2 folder..."
cp -rf ${OUT}/arch/arm64/boot/Image.gz ${AK2}/kernel/
cp -rf ${OUT}/arch/arm64/boot/dts/qcom/${DTB}-treble.dtb ${AK2}/treble-supported/${DTB}.dtb
cp -rf ${OUT}/arch/arm64/boot/dts/qcom/${DTB}-nontreble.dtb ${AK2}/treble-unsupported/${DTB}.dtb

echo " - You're done, smart boy!"
tg_sendinfo "${MSG} Completed!"

# TODO: Pack the kernel? How?
