#!/usr/bin/env bash
#
# Copyright (C) 2017-2018 Albert I (krasCGQ)
# Copyright (C) 2017-2018 The AIMROM Project
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Device: Xiaomi Redmi Note 4/4X Snapdragon (mido)
device="device/xiaomi/mido";
kernel="kernel/xiaomi/msm8953";
vendor="vendor/xiaomi";

# HALs
audio="hardware/qcom/audio-caf/msm8996";
display="hardware/qcom/display-caf/msm8996";
media="hardware/qcom/media-caf/msm8996";

# Toolchain
toolchain="prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-7.x";

# Default branches
default="oreo-mr1";
hals="staging/oreo-mr1-caf-8996";

# Clone
[[ ! -d ${device} ]] && git clone git://github.com/KudProject/device_xiaomi_mido -b rebase/lineage-15.1 ${device};
[[ ! -d ${kernel} ]] && git clone git://github.com/KudProject/kernel_xiaomi_msm8953 -b ${default} ${kernel};
[[ ! -d ${vendor} ]] && git clone git://github.com/KudProject/proprietary_vendor_xiaomi -b kek ${vendor} --depth=1;
[[ ! -d ${toolchain} ]] && git clone git://github.com/krasCGQ/aarch64-linux-android -b opt-7.x ${toolchain} --depth=1;

# Update
if [[ -d ${device} ]]; then
    cd ${device};
    git fetch origin rebase/lineage-15.1;
    git reset --hard origin/rebase/lineage-15.1;
    git clean -dfx;
    cd ../../..;
fi;
if [[ -d ${kernel} ]]; then
    cd ${kernel};
    git pull origin ${default};
    cd ../../..;
fi;
if [[ -d ${vendor} ]]; then
    cd ${vendor};
    git fetch origin kek --depth=1;
    git reset --hard FETCH_HEAD;
    git clean -dfx;
    cd ../..;
fi;
if [[ -d ${toolchain} ]]; then
    cd ${toolchain};
    git fetch origin opt-7.x --depth=1;
    git reset --hard FETCH_HEAD;
    git clean -dfx;
    cd ../../../../..;
fi;
if [[ -d ${audio} ]]; then
    cd ${audio};
    git fetch git://github.com/KudProject/hardware_qcom_audio ${hals};
    git reset --hard FETCH_HEAD;
    cd ../../../..;
fi;
if [[ -d ${display} ]]; then
    cd ${display};
    git fetch git://github.com/KudProject/hardware_qcom_display ${hals};
    git reset --hard FETCH_HEAD;
    cd ../../../..;
fi;
if [[ -d ${media} ]]; then
    cd ${media};
    git fetch git://github.com/KudProject/hardware_qcom_media ${hals};
    git reset --hard FETCH_HEAD;
    cd ../../../..;
fi;

# Device Tree Patch
if [[ -d ${device} ]]; then
    cd ${device};
    mv -f lineage.mk aim.mk;
    sed -i "s/lineage/aim/g" aim.mk;
    printf "\nTARGET_KERNEL_CROSS_COMPILE_PREFIX := aarch64-opt-linux-android-" >> BoardConfig.mk;
    printf "\nKERNEL_TOOLCHAIN := /home/aimrom/aim/${toolchain}/bin" >> BoardConfig.mk;
    cd ../../..;
fi;
