#!/usr/bin/env bash
# Battery info wrapper for i3status
# Copyright (C) 2019 Albert I (krasCGQ)
# SPDX-License-Identifier: GPL-3.0-or-later

# Power supply sysclass path
POWER=/sys/class/power_supply

# Check for battery status
battery_status() {
    # Add space in between if more than a battery is present
    [[ -n ${STATUS} ]] && STATUS+=" "

    # Display current percentage if exist, otherwise report it down
    [[ $(cat ${POWER}/"${1}"/present) -eq 1 ]] && \
        STATUS+="${1/BAT/}:$(cat ${POWER}/"${1}"/capacity)%" || \
        STATUS+="${1/BAT/}:DOWN"
}

# Recursively find present batteries
for BAT in $(find ${POWER} -name 'BAT*' | sort -n); do
    battery_status "$(basename "${BAT}")"
done

# Additionally, check if we're charging or not
[[ $(cat ${POWER}/ACAD/online) -eq 1 ]] && \
    STATUS+=" "

# Final output
echo " ${STATUS}"
