#!/usr/bin/env sh
# Clang C compiler alias for GCC
# Copyright (C) 2018-2019 Albert I (krasCGQ)
# SPDX-License-Identifier: GPL-3.0-or-later

# This script is designed to be executed on several environments that hardcoded
# use of GCC while Clang can also be used to compile codes (i.e. DKMS).
# Please bind mount this file with any app of your choice, i.e.:
#     mount --bind /path/to/this/gcc/script /usr/bin/gcc

# Default distribution's Clang path; abort if it doesn't exist
DEFAULT_PATH=$(command -v clang || exit 1)

# Define custom Clang path if any
CLANG_PATH=/opt/kud/clang/bin/clang

# Check if compiler exists and executable
if [ -x "$CLANG_PATH" ]; then
    CLANG_EXECUTABLE=${CLANG_PATH}
elif [ -x "$DEFAULT_PATH" ]; then
    CLANG_EXECUTABLE=${DEFAULT_PATH}
fi

# Actual command - please note that "$@" can't be quoted
# shellcheck disable=SC2068
$CLANG_EXECUTABLE $@
