#!/usr/bin/env bash

TZ=Asia/Makassar
GPG_TTY=$(tty)
KBUILD_BUILD_USER=krasCGQ
KBUILD_BUILD_HOST=KudProject

export TZ GPG_TTY KBUILD_BUILD_USER KBUILD_BUILD_HOST

eval "$(ssh-agent -s)"
ssh-add "${HOME}"/.ssh/id_ed25519
