#!/hint/bash
#
# SPDX-FileCopyrightText: 2017-2022, 2024 Albert I (krasCGQ)
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Environment setup for my notebook
#

# Set path to script directory depending on which shell we use
if [[ -n $BASH ]]; then
    # Bash
    SCRIPT_DIR=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
elif [[ -n $ZSH_VERSION ]]; then
    # Zsh
    # shellcheck disable=SC2154,SC2296
    SCRIPT_DIR=$(dirname "${(%):-%x}")
else
    echo "! Unsupported shell. Exiting." >&2
    return 1
fi
SCRIPT_DIR=$(dirname "$SCRIPT_DIR")
export SCRIPT_DIR

# Import common environment script
source "$SCRIPT_DIR/env/common"

# This is intended to quickly hexedit binaries from older Android version to run on a newer one
mk_alias sys2sbin 'sed -i "s|/system/bin/linker64|/sbin/linker64\x0\x0\x0\x0\x0\x0|g"'

# Shortcut to run kernel build script
mk_alias ak-build "bash $SCRIPT_DIR/tasks/kernel.bash"

if [[ -z $TMUX ]]; then
    # Export new PATH containing Android SDK binaries, if present
    ANDROID_SDK=/opt/android-sdk
    if pushd $ANDROID_SDK/build-tools &>/dev/null; then
        for VERSION in ./*; do
            VERSION=${VERSION/.\//}
            # Filter out anything that doesn't consist of only integers
            if [[ $VERSION =~ [0-9.] ]]; then
                PATH=$PATH:$ANDROID_SDK/build-tools/$VERSION
                break
            fi
        done
        unset VERSION
        popd >/dev/null || true
    fi
    # There are instances where platform-tools might have been added to PATH already
    [[ -d $ANDROID_SDK/platform-tools && ! $PATH =~ $ANDROID_SDK/platform-tools ]] &&
        PATH=$PATH:$ANDROID_SDK/platform-tools
    unset ANDROID_SDK
fi

# Convert all FLAC, WAV, and/or AIFF files in current folder to Opus
convert_to_opus() {
    local AUDIO IS_AUDIO_CONVERTED=false

    # Ask to install opus-tools package if opusenc doesn't exist
    if command -v opusenc >/dev/null; then
        _pr_warn "Please install opus-tools package before continuing."
        return 1
    fi

    for AUDIO in ./*; do
        case "$AUDIO" in
        *.aiff | *.flac | *.wav)
            # Not supporting wildcards for converting
            opusenc --quiet --vbr --bitrate 192 --comp 10 --expect-loss 0 \
                "$AUDIO" "$(basename "$AUDIO" | sed 's/\(.*\)\..*/\1/').ogg" || return 1
            IS_AUDIO_CONVERTED=true
            ;;
        esac
    done

    # If no supported files are converted, return non-zero status
    $IS_AUDIO_CONVERTED
}

# Play from HDMI capture device using mpv
play_hdmi_capture() {
    local DEFAULT_ARGS DEFAULT_PARAMS DEVICE DEVICE_PARAMS=()

    # Default arguments that are always passed
    DEFAULT_ARGS=(
        '--config=no'              # don't load local mpv.conf
        '--load-scripts=no'        # disable loading of LUA scripts
        '--profile=low-latency'    # inherit low latency profile
        '--correct-pts=no'         # helps with frame rate signaling issues
        '--opengl-glfinish=yes'    # helps reducing graphics driver buffering
        '--opengl-swapinterval=0'  # helps reducing graphics driver buffering
    )

    # Default parameters, that is, shared with both capture devices
    DEFAULT_PARAMS=(
        # Without this option, mpv will output no audio at all
        '--demuxer-lavf-o-append=timestamps=2'
        # Always pick highest resolution provided by capture device (currently 1080p)
        '--demuxer-lavf-o-append=video_size=1920x1080'
    )

    if [[ -e /dev/v4l/by-id/usb-AVerMedia_AVerMedia_USB_Device_53106217017740-video-index0 ]]; then
        # Video4Linux v2 device and its audio sink
        DEVICE='AVerMedia_AVerMedia_USB_Device_53106217017740'
        # Select 60 fps even though these should be the default anyway
        DEVICE_PARAMS+=('--demuxer-lavf-o-append=framerate=60')
        DEVICE_PARAMS+=('--container-fps-override=60')
    elif [[ -e /dev/v4l/by-id/usb-MACROSILICON_USB_Video-video-index0 ]]; then
        # Video4Linux v2 device and its audio sink
        DEVICE='MACROSILICON_USB_Video'
        # Explicitly use MJPEG output format (it defaults to H.264 1080p5)
        DEVICE_PARAMS+=('--demuxer-lavf-o-append=input_format=mjpeg')
        # Force 30 fps output due to tearing issues with this capture device
        DEVICE_PARAMS+=('--demuxer-lavf-o-append=framerate=30')
        DEVICE_PARAMS+=('--container-fps-override=30')
    else
        _pr_warn "No capture device found for this session."
        return
    fi

    mpv "${DEFAULT_ARGS[@]}" "${DEFAULT_PARAMS[@]}" "${DEVICE_PARAMS[@]}" \
        --audio-file="av://pulse:alsa_input.usb-$DEVICE-02.analog-stereo" \
        "av://v4l2:/dev/v4l/by-id/usb-$DEVICE-video-index0" \
        "$@"
}
