#!/hint/bash
#
# SPDX-FileCopyrightText: 2017-2020, 2022, 2024 Albert I (krasCGQ)
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Environment setup for my servers
#

# Set path to script directory depending on which shell we use
if [[ -n $BASH ]]; then
    # Bash
    SCRIPT_DIR=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
elif [[ -n $ZSH_VERSION ]]; then
    # Zsh
    # shellcheck disable=SC2154,SC2296
    SCRIPT_DIR=$(dirname "${(%):-%x}")
else
    echo "! Unsupported shell. Exiting." >&2
    return 1
fi
SCRIPT_DIR=$(dirname "$SCRIPT_DIR")
export SCRIPT_DIR

# Import common environment script
source "$SCRIPT_DIR/env/common"

# Force prompts to be in color regardless of compatibility
mk_alias tmux 'force_color_prompt=yes tmux'

# Shortcut for ssh-agent setup
ssh_setup() {
    # Do an unconditional check
    if [[ ! -f $HOME/.ssh/id_ed25519 ]]; then
        _pr_warn "Please generate an SSH key before using this function."
        return 1
    fi

    # The actual setup is here
    eval "$(ssh-agent -s)"
    ssh-add "$HOME"/.ssh/id_ed25519
}
