#!/usr/bin/env bash
# Environment setup for my VPS
# Copyright (C) 2018 Albert I (krasCGQ)
# SPDX-License-Identifier: GPL-3.0-or-later

# Don't setup if not in correct environment
[[ $(whoami) != kud || $(hostname) != wafuu.id ]] && return 1

# Import common environment script
# shellcheck source=/dev/null
. "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"/common

# Aliases
alias tmux='force_color_prompt=yes tmux'
alias update='sudo su -c "apt update && apt-get dist-upgrade -y"'
